name: aprendiendo-github-actions
run-name: ${{ github.actor }} esta aprendiendo GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install -g check-bats-version
      - run: bats -v
